// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus')['ElButton']
    ElCard: typeof import('element-plus')['ElCard']
    ElDatePicker: typeof import('element-plus')['ElDatePicker']
    ElDescriptions: typeof import('element-plus')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus')['ElDialog']
    ElDropdown: typeof import('element-plus')['ElDropdown']
    ElDropdownItem: typeof import('element-plus')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus')['ElEmpty']
    ElForm: typeof import('element-plus')['ElForm']
    ElFormItem: typeof import('element-plus')['ElFormItem']
    ElIcon: typeof import('element-plus')['ElIcon']
    ElInput: typeof import('element-plus')['ElInput']
    ElLink: typeof import('element-plus')['ElLink']
    ElMain: typeof import('element-plus')['ElMain']
    ElMessage: typeof import('element-plus')['ElMessage']
    ElTable: typeof import('element-plus')['ElTable']
    ElTableColumn: typeof import('element-plus')['ElTableColumn']
    ElTag: typeof import('element-plus')['ElTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
} 